// eslint-disable-next-line import/no-anonymous-default-export
export default {
  login: 'jadijadi',
  id: 1290639,
  node_id: 'MDQ6VXNlcjEyOTA2Mzk=',
  avatar_url: 'https://avatars.githubusercontent.com/u/1290639?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/jadijadi',
  html_url: 'https://github.com/jadijadi',
  followers_url: 'https://api.github.com/users/jadijadi/followers',
  following_url: 'https://api.github.com/users/jadijadi/following{/other_user}',
  gists_url: 'https://api.github.com/users/jadijadi/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/jadijadi/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/jadijadi/subscriptions',
  organizations_url: 'https://api.github.com/users/jadijadi/orgs',
  repos_url: 'https://api.github.com/users/jadijadi/repos',
  events_url: 'https://api.github.com/users/jadijadi/events{/privacy}',
  received_events_url: 'https://api.github.com/users/jadijadi/received_events',
  type: 'User',
  site_admin: false,
  name: 'Jadi',
  company: null,
  blog: 'www.jadi.net',
  location: null,
  email: null,
  hireable: true,
  bio: 'Into freedom',
  twitter_username: 'jadi',
  public_repos: 65,
  public_gists: 8,
  followers: 12122,
  following: 23,
  created_at: '2011-12-28T15:29:15Z',
  updated_at: '2022-12-21T07:17:39Z',
}
